<?php

return [
	// hooks
	'add_filter'                  => '',
	'_wp_call_all_hook'           => '',
	'apply_filters'               => '',
	'apply_filters_deprecated'    => '',
	'apply_filters_ref_array'     => '',
	'has_filter'                  => '',
	'remove_filter'               => '',
	'remove_all_filters'          => '',
	'current_filter'              => '',
	'doing_filter'                => '',
	'did_filter'                  => '',
	'add_action'                  => '',
	'do_action'                   => '',
	'do_action_deprecated'        => '',
	'do_action_ref_array'         => '',
	'has_action'                  => '',
	'remove_action'               => '',
	'remove_all_actions'          => '',
	'current_action'              => '',
	'doing_action'                => '',
	'did_action'                  => '',
	'wp_register_plugin_realpath' => '',
	'plugin_basename'             => '',
	'plugin_dir_path'             => '',
	'plugin_dir_url'              => '',
	'register_activation_hook'    => '',
	'register_deactivation_hook'  => '',
	'register_uninstall_hook'     => '',
	'_wp_filter_build_unique_id'  => '',
];
