<?php

return [
	// Нужна для script/style tag helpers и классов WP_Scripts/WP_Styles.
	'current_theme_supports' => '',
	// Реестр theme-support фичей в памяти.
	'add_theme_support'             => '',
	'get_theme_support'             => '',
	'remove_theme_support'          => '',
	'_remove_theme_support'         => '',
	'register_theme_feature'        => '',
	'get_registered_theme_features' => '',
	'get_registered_theme_feature'  => '',
	'create_initial_theme_features' => '',
	// Missing in config, kept for visibility because not suitable for isolated PHPUnit env:
	// 'wp_get_themes'                      => '', // why: theme discovery + filesystem scan/runtime cache.
	// 'wp_get_theme'                       => '', // why: theme discovery + filesystem scan/runtime cache.
	// 'wp_clean_themes_cache'              => '', // why: theme discovery + filesystem scan/runtime cache.
	// 'is_child_theme'                     => '', // why: path/theme discovery runtime dependency.
	// 'get_stylesheet'                     => '', // why: path/theme discovery runtime dependency.
	// 'get_stylesheet_directory'           => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_stylesheet_directory_uri'       => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_stylesheet_uri'                 => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_locale_stylesheet_uri'          => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_template'                       => '', // why: path/theme discovery runtime dependency.
	// 'get_template_directory'             => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_template_directory_uri'         => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_theme_roots'                    => '', // why: path/theme discovery runtime dependency.
	// 'register_theme_directory'           => '', // why: theme directory registration/runtime filesystem dependency.
	// 'search_theme_directories'           => '', // why: filesystem scan dependency.
	// 'get_theme_root'                     => '', // why: path/theme discovery runtime dependency.
	// 'get_theme_root_uri'                 => '', // why: path/url resolution tied to real theme directories/filesystem.
	// 'get_raw_theme_root'                 => '', // why: path/theme discovery runtime dependency.
	// 'locale_stylesheet'                  => '', // why: locale + theme path runtime dependency.
	// 'switch_theme'                       => '', // why: full theme switch/bootstrap flow.
	// 'validate_current_theme'             => '', // why: full theme switch/bootstrap flow.
	// 'validate_theme_requirements'        => '', // why: full theme switch/bootstrap flow.
	// 'check_theme_switched'               => '', // why: full theme switch/bootstrap flow.
	// 'get_theme_mods'                     => '', // why: options DB storage dependency.
	// 'get_theme_mod'                      => '', // why: options DB storage dependency.
	// 'set_theme_mod'                      => '', // why: options DB storage dependency.
	// 'remove_theme_mod'                   => '', // why: options DB storage dependency.
	// 'remove_theme_mods'                  => '', // why: options DB storage dependency.
	// 'get_header_textcolor'               => '', // why: customizer/media/theme runtime dependency.
	// 'header_textcolor'                   => '', // why: customizer/media/theme runtime dependency.
	// 'display_header_text'                => '', // why: customizer/media/theme runtime dependency.
	// 'has_header_image'                   => '', // why: customizer/media/theme runtime dependency.
	// 'get_header_image'                   => '', // why: customizer/media/theme runtime dependency.
	// 'get_header_image_tag'               => '', // why: customizer/media/theme runtime dependency.
	// 'the_header_image_tag'               => '', // why: customizer/media/theme runtime dependency.
	// '_get_random_header_data'            => '', // why: customizer/media/theme runtime dependency.
	// 'get_random_header_image'            => '', // why: customizer/media/theme runtime dependency.
	// 'is_random_header_image'             => '', // why: customizer/media/theme runtime dependency.
	// 'header_image'                       => '', // why: customizer/media/theme runtime dependency.
	// 'get_uploaded_header_images'         => '', // why: customizer/media/theme runtime dependency.
	// 'get_custom_header'                  => '', // why: customizer/media/theme runtime dependency.
	// 'register_default_headers'           => '', // why: customizer/media/theme runtime dependency.
	// 'unregister_default_headers'         => '', // why: customizer/media/theme runtime dependency.
	// 'has_header_video'                   => '', // why: customizer/media/theme runtime dependency.
	// 'get_header_video_url'               => '', // why: customizer/media/theme runtime dependency.
	// 'the_header_video_url'               => '', // why: customizer/media/theme runtime dependency.
	// 'get_header_video_settings'          => '', // why: customizer/media/theme runtime dependency.
	// 'has_custom_header'                  => '', // why: customizer/media/theme runtime dependency.
	// 'is_header_video_active'             => '', // why: customizer/media/theme runtime dependency.
	// 'get_custom_header_markup'           => '', // why: customizer/media/theme runtime dependency.
	// 'the_custom_header_markup'           => '', // why: customizer/media/theme runtime dependency.
	// 'get_background_image'               => '', // why: customizer/media/theme runtime dependency.
	// 'background_image'                   => '', // why: customizer/media/theme runtime dependency.
	// 'get_background_color'               => '', // why: customizer/media/theme runtime dependency.
	// 'background_color'                   => '', // why: customizer/media/theme runtime dependency.
	// '_custom_background_cb'              => '', // why: customizer/media/theme runtime dependency.
	// '_custom_logo_header_styles'         => '', // why: customizer/media/theme runtime dependency.
	// 'wp_custom_css_cb'                   => '', // why: posts DB + customizer runtime dependency.
	// 'wp_get_custom_css_post'             => '', // why: posts DB + customizer runtime dependency.
	// 'wp_get_custom_css'                  => '', // why: posts DB + customizer runtime dependency.
	// 'wp_update_custom_css_post'          => '', // why: posts DB + customizer runtime dependency.
	// 'add_editor_style'                   => '', // why: stylesheet path resolution/filesystem dependency.
	// 'remove_editor_styles'               => '', // why: stylesheet path resolution/filesystem dependency.
	// 'get_editor_stylesheets'             => '', // why: stylesheet path resolution/filesystem dependency.
	// 'get_theme_starter_content'          => '', // why: theme starter-content runtime dependency.
	// 'require_if_theme_supports' => '', // why: requires arbitrary file include from runtime path.
	// '_wp_customize_include'              => '', // why: customizer request/session/runtime dependency.
	// '_wp_customize_publish_changeset'    => '', // why: customizer request/session/runtime dependency.
	// '_wp_customize_changeset_filter_insert_post_data' => '', // why: customizer request/session/runtime dependency.
	// '_wp_customize_loader_settings'      => '', // why: customizer request/session/runtime dependency.
	// 'wp_customize_url'                   => '', // why: customizer request/session/runtime dependency.
	// 'wp_customize_support_script'        => '', // why: customizer request/session/runtime dependency.
	// 'is_customize_preview'               => '', // why: customizer request/session/runtime dependency.
	// '_wp_keep_alive_customize_changeset_dependent_auto_drafts' => '', // why: customizer request/session/runtime dependency.
	// '_delete_attachment_theme_mod'       => '', // why: attachment + theme_mod storage runtime dependency.
	// 'wp_is_block_theme'                => '', // why: depends on WP_Theme + real theme filesystem.
	// '_add_default_theme_supports'      => '', // why: depends on WP_Theme + real theme filesystem.
	// 'wp_theme_get_element_class_name' => '', // why: requires WP_Theme_JSON class/runtime not included.
];
