<?php

return [
	'zeroise'                             => '0.71',
	'trailingslashit'                     => '1.2.0',
	'untrailingslashit'                   => '2.2.0',
	'sanitize_key'                        => '3.0.0',
	'wp_slash'                            => '3.6.0',
	'wp_parse_str'                        => '2.2.1',
	'sanitize_text_field'                 => '2.9.0',
	'_sanitize_text_fields'               => '4.7.0',
	'wp_pre_kses_less_than'               => '2.3.0',
	'wp_pre_kses_less_than_callback'      => '2.3.0',
	'wp_strip_all_tags'                   => '2.9.0',
	'wpautop'                             => '0.71',
	'wptexturize'                         => '0.71',
	'wptexturize_primes'                  => '4.3.0',
	'is_email'                            => '0.71',
	'wp_check_invalid_utf8'               => '2.8.0',
	'_wptexturize_pushpop_element'        => '2.9.0',
	'wp_html_split'                       => '4.2.4',
	'get_html_split_regex'                => '4.4.0',
	'_get_wptexturize_split_regex'        => '4.4.0',
	'_get_wptexturize_shortcode_regex'    => '4.4.0',
	'wp_replace_in_html_tags'             => '4.2.3',
	'_autop_newline_preservation_helper'  => '3.1.0',
	'shortcode_unautop'                   => '2.9.0',
	'seems_utf8'                          => '1.2.1',
	'_wp_specialchars'                    => '1.2.2',
	'wp_specialchars_decode'              => '2.8.0',
	'utf8_uri_encode'                     => '1.5.0',
	'remove_accents'                      => '1.2.1',
	'sanitize_file_name'                  => '2.1.0',
	'sanitize_user'                       => '2.0.0',
	'sanitize_title'                      => '1.0.0',
	'sanitize_title_for_query'            => '3.1.0',
	'sanitize_title_with_dashes'          => '1.2.0',
	'sanitize_sql_orderby'                => '2.5.1',
	'sanitize_html_class'                 => '2.8.0',
	'sanitize_locale_name'                => '6.2.1',
	'convert_chars'                       => '0.71',
	'convert_invalid_entities'            => '4.3.0',
	'balanceTags'                         => '0.71 mockable',
	'force_balance_tags'                  => '2.0.4',
	'format_to_edit'                      => '0.71',
	'backslashit'                         => '0.71',
	'addslashes_gpc'                      => '0.71',
	'stripslashes_deep'                   => '2.0.0',
	'stripslashes_from_strings_only'      => '4.4.0',
	'urlencode_deep'                      => '2.2.0',
	'rawurlencode_deep'                   => '3.4.0',
	'urldecode_deep'                      => '4.4.0',
	'antispambot'                         => '0.71',
	'make_clickable'                      => '0.71',
	'_make_url_clickable_cb'              => '2.3.2',
	'_make_web_ftp_clickable_cb'          => '2.3.2',
	'_make_email_clickable_cb'            => '2.3.2',
	'_make_clickable_rel_attr'            => '6.2.0',
	'_split_str_by_whitespace'            => '3.4.0',
	'wp_rel_callback'                     => '5.3.0',
	'wp_rel_nofollow'                     => '1.5.0',
	'translate_smiley'                    => '2.8.0',
	'convert_smilies'                     => '0.71 mockable',
	'wp_iso_descrambler'                  => '1.2.0',
	'_wp_iso_convert'                     => '3.1.0',
	'get_gmt_from_date'                   => '1.2.0',
	'get_date_from_gmt'                   => '1.2.0',
	'iso8601_timezone_to_offset'          => '1.5.0',
	'iso8601_to_datetime'                 => '1.5.0',
	'sanitize_email'                      => '1.5.0',
	'human_time_diff'                     => '1.5.0',
	'wp_trim_excerpt'                     => '1.5.0',
	'wp_trim_words'                       => '3.3.0',
	'ent2ncr'                             => '1.5.1',
	'format_for_editor'                   => '4.3.0',
	'_deep_replace'                       => '2.8.1',
	'esc_url'                             => '2.8.0',
	'esc_url_raw'                         => '2.8.0',
	'sanitize_url'                        => '2.3.1',
	'htmlentities2'                       => '1.2.2',
	'esc_js'                              => '2.8.0',
	'esc_html'                            => '2.8.0',
	'esc_attr'                            => '2.8.0',
	'esc_textarea'                        => '3.1.0',
	'esc_xml'                             => '5.5.0',
	'tag_escape'                          => '2.5.0',
	'wp_make_link_relative'               => '2.1.0',
	'map_deep'                            => '4.4.0',
	'wp_sprintf'                          => '2.5.0',
	'wp_sprintf_l'                        => '2.5.0',
	'wp_html_excerpt'                     => '2.5.0',
	'links_add_base_url'                  => '2.7.0',
	'_links_add_base'                     => '2.7.0',
	'links_add_target'                    => '2.7.0',
	'_links_add_target'                   => '2.7.0',
	'normalize_whitespace'                => '2.7.0',
	'sanitize_textarea_field'             => '4.7.0',
	'wp_basename'                         => '3.1.0',
	'sanitize_mime_type'                  => '3.1.3',
	'sanitize_trackback_urls'             => '3.4.0',
	'wp_unslash'                          => '3.6.0',
	'get_url_in_content'                  => '3.6.0',
	'wp_spaces_regexp'                    => '4.0.0',
	'wp_encode_emoji'                     => '4.2.0',
	'wp_staticize_emoji'                  => '4.2.0',
	'wp_staticize_emoji_for_email'        => '4.2.0',
	'_wp_emoji_list'                      => '4.9.0',
	'url_shorten'                         => '1.2.0',
	'sanitize_hex_color'                  => '3.4.0',
	'sanitize_hex_color_no_hash'          => '3.4.0',
	'maybe_hash_hex_color'                => '3.4.0',
	'capital_P_dangit'                    => '3.0.0',
];

/*
Not suitable in isolated PHPUnit env (dependency/runtime coupling):

wp_rel_ugc                          // why: too many dependencies
wp_rel_nofollow_callback            // why: deprecated
wp_targeted_link_rel                // why: deprecated
wp_targeted_link_rel_callback       // why: deprecated
wp_init_targeted_link_rel_filters   // why: deprecated
wp_remove_targeted_link_rel_filters // why: deprecated
esc_sql                             // why: depends on $wpdb
sanitize_option                     // why: depends on $wpdb + options/roles/i18n runtime chain
wp_pre_kses_block_attributes        // why: depends on block parser (maybe can be implemented later)
wp_enqueue_emoji_styles             // why: wp_add_inline_style dependency
print_emoji_detection_script        // why: _print_emoji_detection_script dependency
_print_emoji_detection_script       // why: file_get_contents dependency
*/
