<?php

return [
	'add_filter'                  => '0.71',
	'_wp_call_all_hook'           => '2.5.0',
	'apply_filters'               => '0.71',
	'apply_filters_deprecated'    => '4.6.0',
	'apply_filters_ref_array'     => '3.0.0',
	'has_filter'                  => '2.5.0',
	'remove_filter'               => '1.2.0',
	'remove_all_filters'          => '2.7.0',
	'current_filter'              => '2.5.0',
	'doing_filter'                => '3.9.0',
	'did_filter'                  => '6.1.0',
	'add_action'                  => '1.2.0',
	'do_action'                   => '1.2.0',
	'do_action_deprecated'        => '4.6.0',
	'do_action_ref_array'         => '2.1.0',
	'has_action'                  => '2.5.0',
	'remove_action'               => '1.2.0',
	'remove_all_actions'          => '2.7.0',
	'current_action'              => '3.9.0',
	'doing_action'                => '3.9.0',
	'did_action'                  => '2.1.0',
	'wp_register_plugin_realpath' => '3.9.0',
	'plugin_basename'             => '1.5.0',
	'plugin_dir_path'             => '2.8.0',
	'plugin_dir_url'              => '2.8.0',
	'register_activation_hook'    => '2.0.0',
	'register_deactivation_hook'  => '2.0.0',
	'register_uninstall_hook'     => '2.7.0',
	'_wp_filter_build_unique_id'  => '2.2.3',
];
