<?php
/**
 * Configuration for the WP Copy parser.
 * Filenames and functions to be copied from the WordPress core.
 *
 * Where array key is relative path to the WP core file and values are functions names.
 */
return [
	'wp-includes/formatting.php' => [
		'zeroise'                             => '',
		'trailingslashit'                     => '',
		'untrailingslashit'                   => '',
		'sanitize_key'                        => '',
		'wp_slash'                            => '',
		'wp_parse_str'                        => '',
		'sanitize_text_field'                 => '',
		'_sanitize_text_fields'               => '',
		'wp_pre_kses_less_than'               => '',
		'wp_pre_kses_less_than_callback'      => '',
		'wp_strip_all_tags'                   => '',
		'wpautop'                             => '',
		'wptexturize'                         => '',
		'wptexturize_primes'                  => '',
		'is_email'                            => '',
		'wp_check_invalid_utf8'               => '',
		'_wptexturize_pushpop_element'        => '',
		'wp_html_split'                       => '',
		'get_html_split_regex'                => '',
		'_get_wptexturize_split_regex'        => '',
		'_get_wptexturize_shortcode_regex'    => '',
		'wp_replace_in_html_tags'             => '',
		'_autop_newline_preservation_helper'  => '',
		'shortcode_unautop'                   => '',
		'seems_utf8'                          => '',
		'_wp_specialchars'                    => '',
		'wp_specialchars_decode'              => '',
		'utf8_uri_encode'                     => '',
		'remove_accents'                      => '',
		'sanitize_file_name'                  => '',
		'sanitize_user'                       => '',
		'sanitize_title'                      => '',
		'sanitize_title_for_query'            => '',
		'sanitize_title_with_dashes'          => '',
		'sanitize_sql_orderby'                => '',
		'sanitize_html_class'                 => '',
		'sanitize_locale_name'                => '',
		'convert_chars'                       => '',
		'convert_invalid_entities'            => '',
		'balanceTags'                         => '',
		'force_balance_tags'                  => '',
		'format_to_edit'                      => '',
		'backslashit'                         => '',
		'addslashes_gpc'                      => '',
		'stripslashes_deep'                   => '',
		'stripslashes_from_strings_only'      => '',
		'urlencode_deep'                      => '',
		'rawurlencode_deep'                   => '',
		'urldecode_deep'                      => '',
		'antispambot'                         => '',
		'make_clickable'                      => '',
		'_make_url_clickable_cb'              => '',
		'_make_web_ftp_clickable_cb'          => '',
		'_make_email_clickable_cb'            => '',
		'_make_clickable_rel_attr'            => '',
		'_split_str_by_whitespace'            => '',
		'wp_rel_callback'                     => '',
		'wp_rel_nofollow'                     => '',
		// 'wp_rel_nofollow_callback'            => '', // deprecated
		// 'wp_rel_ugc'                          => '', // too many dependencies
		// 'wp_targeted_link_rel'                => '', // deprecated
		// 'wp_targeted_link_rel_callback'       => '', // deprecated
		// 'wp_init_targeted_link_rel_filters'   => '', // deprecated
		// 'wp_remove_targeted_link_rel_filters' => '', // deprecated
		'translate_smiley'                    => '',
		'convert_smilies'                     => '',
		'wp_iso_descrambler'                  => '',
		'_wp_iso_convert'                     => '',
		'get_gmt_from_date'                   => '',
		'get_date_from_gmt'                   => '',
		'iso8601_timezone_to_offset'          => '',
		'iso8601_to_datetime'                 => '',
		'sanitize_email'                      => '',
		'human_time_diff'                     => '',
		'wp_trim_excerpt'                     => '',
		'wp_trim_words'                       => '',
		'ent2ncr'                             => '',
		'format_for_editor'                   => '',
		'_deep_replace'                       => '',
		// 'esc_sql'                             => '', // dependency on $wpdb
		'esc_url'                             => '',
		'esc_url_raw'                         => '',
		'sanitize_url'                        => '',
		'htmlentities2'                       => '',
		'esc_js'                              => '',
		'esc_html'                            => '',
		'esc_attr'                            => '',
		'esc_textarea'                        => '',
		'esc_xml'                             => '',
		'tag_escape'                          => '',
		'wp_make_link_relative'               => '',
		// 'sanitize_option'                     => '',
		'map_deep'                            => '',
		// 'wp_pre_kses_block_attributes'        => '', // why: dependency on block parser (maybe can be implemented later)
		'wp_sprintf'                          => '',
		'wp_sprintf_l'                        => '',
		'wp_html_excerpt'                     => '',
		'links_add_base_url'                  => '',
		'_links_add_base'                     => '',
		'links_add_target'                    => '',
		'_links_add_target'                   => '',
		'normalize_whitespace'                => '',
		'sanitize_textarea_field'             => '',
		'wp_basename'                         => '',
		'sanitize_mime_type'                  => '',
		'sanitize_trackback_urls'             => '',
		'wp_unslash'                          => '',
		'get_url_in_content'                  => '',
		'wp_spaces_regexp'                    => '',
		'wp_encode_emoji'                     => '',
		'wp_staticize_emoji'                  => '',
		'wp_staticize_emoji_for_email'        => '',
		'_wp_emoji_list'                      => '',
		'url_shorten'                         => '',
		'sanitize_hex_color'                  => '',
		'sanitize_hex_color_no_hash'          => '',
		'maybe_hash_hex_color'                => '',
		'capital_P_dangit'                    => '',
		// 'wp_enqueue_emoji_styles'             => '', // why: wp_add_inline_style dependency
		// 'print_emoji_detection_script'        => '', // why: _print_emoji_detection_script dependency
		// '_print_emoji_detection_script'       => '', // why: file_get_contents dependency
	],
	'wp-includes/functions.php' => [
		'__return_empty_array'                   => '',
		'__return_empty_string'                  => '',
		'__return_false'                         => '',
		'__return_null'                          => '',
		'__return_true'                          => '',
		'__return_zero'                          => '',
		'_canonical_charset'                     => '',
		'_cleanup_header_comment'                => '',
		'_http_build_query'                      => '',
		'_wp_array_get'                          => '',
		'_wp_array_set'                          => '',
		'_wp_json_convert_string'                => '',
		'_wp_json_prepare_data'                  => '',
		'_wp_json_sanity_check'                  => '',
		'_wp_to_kebab_case'                      => '',
		'add_query_arg'                          => '',
		'bool_from_yn'                           => '',
		'build_query'                            => '',
		'get_allowed_mime_types'                 => '',
		'get_file_data'                          => '',
		'is_serialized'                          => '',
		'is_serialized_string'                   => '',
		'is_utf8_charset'                        => '',
		// 'is_php_version_compatible'              => '', // why: better to leave mockable
		// 'is_wp_version_compatible'               => '', // why: better to leave mockable
		'maybe_serialize'                        => '',
		'maybe_unserialize'                      => '',
		'mbstring_binary_safe_encoding'          => '',
		'path_is_absolute'                       => '',
		'path_join'                              => '',
		'remove_query_arg'                       => '',
		'reset_mbstring_encoding'                => '',
		'validate_file'                          => '',
		'wp_array_slice_assoc'                   => '',
		'wp_check_filetype'                      => '',
		'wp_check_jsonp_callback'                => '',
		'wp_checkdate'                           => '',
		'wp_debug_backtrace_summary'             => '',
		'get_status_header_desc'                 => '',
		'get_tag_regex'                          => '',
		'human_readable_duration'                => '',
		'wp_ext2type'                            => '',
		// 'wp_fast_hash'                           => '', // why: requires sodium
		'wp_filter_object_list'                  => '',
		'wp_find_hierarchy_loop'                 => '',
		'wp_find_hierarchy_loop_tortoise_hare'   => '',
		'wp_fuzzy_number_match'                  => '',
		'wp_generate_uuid4'                      => '',
		'wp_get_default_extension_for_mime_type' => '',
		'wp_get_ext_types'                       => '',
		'wp_get_image_mime'                      => '',
		'wp_get_mime_types'                      => '',
		'wp_get_nocache_headers'                 => '',
		// 'wp_get_wp_version'                      => '', // why: requires full WP file tree via ABSPATH/WPINC
		'wp_is_heic_image_mime_type'             => '',
		'wp_is_numeric_array'                    => '',
		'wp_is_stream'                           => '',
		'wp_is_uuid'                             => '',
		'wp_json_encode'                         => '',
		'wp_json_file_decode'                    => '',
		'wp_list_filter'                         => '',
		'wp_list_pluck'                          => '',
		'wp_list_sort'                           => '',
		'wp_normalize_path'                      => '',
		'wp_parse_args'                          => '',
		'wp_parse_id_list'                       => '',
		'wp_parse_list'                          => '',
		'wp_parse_slug_list'                     => '',
		'wp_privacy_anonymize_data'              => '',
		'wp_privacy_anonymize_ip'                => '',
		'wp_recursive_ksort'                     => '',
		'wp_unique_id'                           => '',
		'wp_unique_id_from_values'               => '',
		'wp_unique_prefixed_id'                  => '',
		'wp_validate_boolean'                    => '',
		// 'wp_verify_fast_hash'                    => '', // not used in this project (legacy branch requires full WP file tree)
		'_deprecated_function'          => '',
		'wp_timezone'                   => '',
		'wp_timezone_string'            => '',
		'current_datetime'              => '',
		'current_time'                  => '',
		'date_i18n'                     => '',
		'mysql2date'                    => '',
		'mysql_to_rfc3339'              => '',
		'number_format_i18n'            => '',
		'size_format'                   => '',
		'_deprecated_argument'          => '',
		'_doing_it_wrong'               => '',
		'wp_trigger_error'              => '',
		'smilies_init'                  => '',
		'force_ssl_admin'               => '',
		'wp_suspend_cache_addition'     => '',
		'wp_allowed_protocols'          => '',
		'wp_date'                       => '',
		// Missing in config, kept for visibility because not suitable for isolated PHPUnit env:
		// '_ajax_wp_die_handler'               => '', // why: requires full HTTP output/wp_die runtime flow.
		// '_config_wp_home'                    => '', // why: mutates global config/runtime state.
		// '_config_wp_siteurl'                 => '', // why: mutates global config/runtime state.
		// '_default_wp_die_handler'            => '', // why: requires full WP request context.
		// '_delete_option_fresh_site'          => '', // why: depends on options lifecycle/full install flow.
		// '_deprecated_class'                  => '', // why: tied to legacy runtime notices/bootstrapping.
		// '_deprecated_constructor'            => '', // why: tied to legacy runtime notices/bootstrapping.
		// '_deprecated_file'                   => '', // why: tied to include/runtime loading flow.
		'_deprecated_hook'                   => '', // note: need as deps
		// '_device_can_upload'                 => '', // why: depends on request headers/client runtime.
		// '_get_non_cached_ids'                => '', // why: requires object-cache/runtime context.
		// '_json_wp_die_handler'               => '', // why: requires full HTTP output/wp_die runtime flow.
		// '_jsonp_wp_die_handler'              => '', // why: requires full HTTP output/wp_die runtime flow.
		// '_mce_set_direction'                 => '', // why: editor/admin runtime dependency.
		// '_scalar_wp_die_handler'             => '', // why: requires full HTTP output/wp_die runtime flow.
		// '_validate_cache_id'                 => '', // why: requires object-cache/runtime context.
		// '_wp_check_alternate_file_names'     => '', // why: filesystem/media upload dependency.
		// '_wp_check_existing_file_names'      => '', // why: filesystem/media upload dependency.
		// '_wp_die_process_input'              => '', // why: requires wp_die request lifecycle.
		// '_wp_mysql_week'                     => '', // why: tied to DB date query behavior.
		// '_wp_timezone_choice_usort_callback' => '', // why: used only with full timezone list UI flow.
		// '_wp_upload_dir'                     => '', // why: filesystem + uploads runtime dependency.
		// '_xml_wp_die_handler'                => '', // why: requires full HTTP output/wp_die runtime flow.
		// '_xmlrpc_wp_die_handler'             => '', // why: requires full XML-RPC runtime flow.
		// 'add_magic_quotes'                   => '', // why: request bootstrap mutation.
		// 'apache_mod_loaded'                  => '', // why: server-environment specific runtime behavior.
		// 'cache_javascript_headers'           => '', // why: HTTP headers/output side effects.
		// 'clean_dirsize_cache'                => '', // why: depends on object-cache/filesystem runtime.
		// 'dead_db'                            => '', // why: DB bootstrap failure handler.
		// 'do_enclose'                         => '', // why: post/media runtime dependency.
		// 'do_favicon'                         => '', // why: request routing/output side effects.
		// 'do_feed'                            => '', // why: request routing/output side effects.
		// 'do_feed_atom'                       => '', // why: request routing/output side effects.
		// 'do_feed_rdf'                        => '', // why: request routing/output side effects.
		// 'do_feed_rss'                        => '', // why: request routing/output side effects.
		// 'do_feed_rss2'                       => '', // why: request routing/output side effects.
		// 'do_robots'                          => '', // why: request routing/output side effects.
		// 'get_dirsize'                        => '', // why: filesystem runtime dependency.
		// 'get_main_network_id'                => '', // why: multisite DB/runtime dependency.
		// 'get_main_site_id'                   => '', // why: multisite DB/runtime dependency.
		// 'get_num_queries'                    => '', // why: DB/runtime dependency.
		// 'get_temp_dir'                       => '', // why: filesystem/environment dependency.
		// 'get_weekstartend'                   => '', // why: option + locale runtime dependency.
		// 'iis7_supports_permalinks'           => '', // why: server-environment specific runtime behavior.
		// 'is_blog_installed'                  => '', // why: DB/runtime dependency.
		// 'is_lighttpd_before_150'             => '', // why: server-environment specific runtime behavior.
		// 'is_main_network'                    => '', // why: multisite DB/runtime dependency.
		// 'is_main_site'                       => '', // why: multisite DB/runtime dependency.
		// 'is_new_day'                         => '', // why: relies on full post loop/global runtime.
		// 'is_site_meta_supported'             => '', // why: DB/runtime dependency.
		// 'nocache_headers'                    => '', // why: HTTP headers/output side effects.
		// 'recurse_dirsize'                    => '', // why: filesystem runtime dependency.
		// 'send_frame_options_header'          => '', // why: HTTP headers/output side effects.
		// 'send_nosniff_header'                => '', // why: HTTP headers/output side effects.
		// 'status_header'                      => '', // why: HTTP headers/output side effects.
		// 'win_is_writable'                    => '', // why: filesystem/environment dependency.
		// 'wp'                                 => '', // why: full WP bootstrap entrypoint.
		// 'wp_admin_headers'                   => '', // why: admin HTTP output/runtime dependency.
		// 'wp_admin_notice'                    => '', // why: admin notice/runtime dependency.
		// 'wp_auth_check'                      => '', // why: auth/cookie/session runtime dependency.
		// 'wp_auth_check_html'                 => '', // why: auth/cookie/session runtime dependency.
		// 'wp_auth_check_load'                 => '', // why: auth/cookie/session runtime dependency.
		// 'wp_cache_get_last_changed'          => '', // why: object-cache runtime dependency.
		// 'wp_cache_set_last_changed'          => '', // why: object-cache runtime dependency.
		// 'wp_check_filetype_and_ext'          => '', // why: filesystem/media validation dependency.
		// 'wp_delete_file'                     => '', // why: filesystem side effects.
		// 'wp_delete_file_from_directory'      => '', // why: filesystem side effects.
		// 'wp_die'                             => '', // why: full request/output lifecycle.
		// 'wp_direct_php_update_button'        => '', // why: admin UI/runtime dependency.
		// 'wp_extract_urls'                    => '', // why: currently not used by this package.
		// 'wp_filesize'                        => '', // why: filesystem runtime dependency.
		// 'wp_get_admin_notice'                => '', // why: admin notice/runtime dependency.
		// 'wp_get_default_update_https_url'    => '', // why: admin/update runtime dependency.
		// 'wp_get_default_update_php_url'      => '', // why: admin/update runtime dependency.
		// 'wp_get_direct_php_update_url'       => '', // why: admin/update runtime dependency.
		// 'wp_get_direct_update_https_url'     => '', // why: admin/update runtime dependency.
		// 'wp_get_http_headers'                => '', // why: remote HTTP/network dependency.
		// 'wp_get_original_referer'            => '', // why: request globals/runtime dependency.
		// 'wp_get_raw_referer'                 => '', // why: request globals/runtime dependency.
		// 'wp_get_referer'                     => '', // why: request globals/runtime dependency.
		// 'wp_get_update_https_url'            => '', // why: admin/update runtime dependency.
		// 'wp_get_update_php_annotation'       => '', // why: admin/update runtime dependency.
		// 'wp_get_update_php_url'              => '', // why: admin/update runtime dependency.
		// 'wp_get_upload_dir'                  => '', // why: filesystem/uploads runtime dependency.
		// 'wp_guess_url'                       => '', // why: server/request runtime dependency.
		// 'wp_is_serving_rest_request'         => '', // why: REST request runtime dependency.
		// 'wp_is_writable'                     => '', // why: filesystem/environment dependency.
		// 'wp_maybe_decline_date'              => '', // why: locale/i18n runtime dependency chain.
		// 'wp_maybe_load_widgets'              => '', // why: widgets runtime bootstrap dependency.
		// 'wp_mkdir_p'                         => '', // why: filesystem side effects.
		// 'wp_nonce_ays'                       => '', // why: nonce/auth request lifecycle dependency.
		// 'wp_nonce_field'                     => '', // why: nonce/auth request lifecycle dependency.
		// 'wp_nonce_url'                       => '', // why: nonce/auth request lifecycle dependency.
		// 'wp_ob_end_flush_all'                => '', // why: output buffering side effects.
		// 'wp_original_referer_field'          => '', // why: request/auth runtime dependency.
		// 'wp_post_preview_js'                 => '', // why: editor/admin runtime dependency.
		// 'wp_privacy_delete_old_export_files' => '', // why: cron/filesystem runtime dependency.
		// 'wp_privacy_exports_dir'             => '', // why: filesystem/uploads runtime dependency.
		// 'wp_privacy_exports_url'             => '', // why: URL + uploads runtime dependency.
		// 'wp_raise_memory_limit'              => '', // why: runtime ini mutation.
		// 'wp_referer_field'                   => '', // why: request/auth runtime dependency.
		// 'wp_remote_fopen'                    => '', // why: remote HTTP/network dependency.
		// 'wp_removable_query_args'            => '', // why: admin/request runtime dependency.
		// 'wp_schedule_delete_old_privacy_export_files' => '', // why: cron runtime dependency.
		// 'wp_scheduled_delete'                => '', // why: cron/runtime dependency.
		// 'wp_send_json'                       => '', // why: HTTP output side effects.
		// 'wp_send_json_error'                 => '', // why: HTTP output side effects.
		// 'wp_send_json_success'               => '', // why: HTTP output side effects.
		// 'wp_site_admin_email_change_notification' => '', // why: option/mail runtime dependency.
		// 'wp_suspend_cache_invalidation'      => '', // why: object-cache runtime dependency.
		// 'wp_timezone_choice'                 => '', // why: admin UI/runtime dependency.
		// 'wp_timezone_override_offset'        => '', // why: option/timezone runtime dependency.
		// 'wp_unique_filename'                 => '', // why: filesystem/uploads runtime dependency.
		// 'wp_update_php_annotation'           => '', // why: admin/update runtime dependency.
		// 'wp_upload_bits'                     => '', // why: filesystem/uploads side effects.
		// 'wp_upload_dir'                      => '', // why: filesystem/uploads runtime dependency.
		// 'wp_widgets_add_menu'                => '', // why: admin/widgets runtime dependency.
		// 'xmlrpc_getpostcategory'             => '', // why: XML-RPC post runtime dependency.
		// 'xmlrpc_getposttitle'                => '', // why: XML-RPC post runtime dependency.
		// 'xmlrpc_removepostdata'              => '', // why: XML-RPC post runtime dependency.
	],
	'wp-includes/kses.php' => [
		'wp_kses'                             => '',
		'wp_kses_one_attr'                    => '',
		'wp_kses_allowed_html'                => '',
		'wp_kses_hook'                        => '',
		'wp_kses_version'                     => '',
		'wp_kses_split'                       => '',
		'wp_kses_uri_attributes'              => '',
		'_wp_kses_split_callback'             => '',
		'wp_kses_split2'                      => '',
		'wp_kses_attr'                        => '',
		'wp_kses_attr_check'                  => '',
		'wp_kses_hair'                        => '',
		'wp_kses_attr_parse'                  => '',
		'wp_kses_hair_parse'                  => '',
		'wp_kses_check_attr_val'              => '',
		'wp_kses_bad_protocol'                => '',
		'wp_kses_no_null'                     => '',
		'wp_kses_stripslashes'                => '',
		'wp_kses_array_lc'                    => '',
		'wp_kses_html_error'                  => '',
		'wp_kses_bad_protocol_once'           => '',
		'wp_kses_bad_protocol_once2'          => '',
		'wp_kses_normalize_entities'          => '',
		'wp_kses_named_entities'              => '',
		'wp_kses_xml_named_entities'          => '',
		'wp_kses_normalize_entities2'         => '',
		'wp_kses_normalize_entities3'         => '',
		'valid_unicode'                       => '',
		'wp_kses_decode_entities'             => '',
		'_wp_kses_decode_entities_chr'        => '',
		'_wp_kses_decode_entities_chr_hexdec' => '',
		'wp_filter_kses'                      => '', // current_filter() dependency
		'wp_kses_data'                        => '', // current_filter() dependency
		'wp_filter_post_kses'                 => '',
		'wp_filter_global_styles_post'        => '',
		'wp_kses_post'                        => '',
		'wp_kses_post_deep'                   => '',
		'wp_filter_nohtml_kses'               => '',
		// 'kses_init'                           => '', // why: depends on current_user_can() runtime capability checks.
		// 'kses_init_filters'                   => '', // why: depends on current_user_can() runtime capability checks.
		// 'kses_remove_filters'                 => '', // make no sense
		'safecss_filter_attr'                 => '',
		'_wp_add_global_attributes'           => '',
		// '_wp_kses_allow_pdf_objects'          => '', // wp_upload_dir() dependency
	],
	'wp-includes/load.php' => [
		'wp_get_development_mode'    => '',
		'wp_get_environment_type'    => '',
		'wp_doing_ajax'              => '',
		'get_current_blog_id'        => '',
		'get_current_network_id'     => '',
		'is_ssl'                     => '',
		'wp_convert_hr_to_bytes'     => '',
		'wp_is_ini_value_changeable' => '',
		'is_wp_error'                => '',
		'is_multisite'               => '',
		'absint'                     => '',
		'timer_float'                => '',
		'timer_start'                => '',
		'timer_stop'                 => '',
		// Missing in config, kept for visibility because not suitable for isolated PHPUnit env:
		// 'is_admin'                                  => '', // why: requires admin bootstrap/request context.
		// 'is_blog_admin'                             => '', // why: requires admin bootstrap/request context.
		// 'is_login'                                  => '', // why: requires login screen/request context.
		// 'is_network_admin'                          => '', // why: requires multisite admin context.
		// 'is_protected_ajax_action'                  => '', // why: protected-endpoint runtime dependency.
		// 'is_protected_endpoint'                     => '', // why: protected-endpoint runtime dependency.
		// 'is_user_admin'                             => '', // why: requires user-admin request context.
		// 'require_wp_db'                             => '', // why: hard DB bootstrap dependency.
		// 'shutdown_action_hook'                      => '', // why: shutdown hook/runtime side effects.
		// 'wp_check_php_mysql_versions'               => '', // why: environment + DB capability checks.
		// 'wp_clone'                                  => '', // why: full bootstrap clone lifecycle.
		// 'wp_debug_mode'                             => '', // why: global runtime/error-handler mutation.
		// 'wp_doing_cron'                             => '', // why: cron/request runtime dependency.
		// 'wp_favicon_request'                        => '', // why: request routing/output dependency.
		// 'wp_finalize_scraping_edited_file_errors'   => '', // why: admin/editor error-scraping runtime.
		// 'wp_fix_server_vars'                        => '', // why: mutates global server runtime.
		// 'wp_get_active_and_valid_plugins'           => '', // why: plugin bootstrap/filesystem dependency.
		// 'wp_get_active_and_valid_themes'            => '', // why: theme bootstrap/filesystem dependency.
		// 'wp_get_mu_plugins'                         => '', // why: mu-plugin filesystem bootstrap dependency.
		// 'wp_get_server_protocol'                    => '', // why: request server-runtime dependency.
		'wp_installing'                                => '', // note: in 99% is not installing, and it used as deps so add it
		// 'wp_is_development_mode'                    => '', // why: full runtime option/env dependency.
		// 'wp_is_file_mod_allowed'                    => '', // why: file-modification policy/runtime dependency.
		// 'wp_is_json_media_type'                     => '', // why: request/content-type runtime dependency.
		// 'wp_is_json_request'                        => '', // why: request/content-type runtime dependency.
		// 'wp_is_jsonp_request'                       => '', // why: request/content-type runtime dependency.
		// 'wp_is_maintenance_mode'                    => '', // why: filesystem + bootstrap dependency.
		// 'wp_is_recovery_mode'                       => '', // why: recovery bootstrap/session dependency.
		// 'wp_is_site_protected_by_basic_auth'        => '', // why: server/auth runtime dependency.
		// 'wp_is_xml_request'                         => '', // why: request/content-type runtime dependency.
		// 'wp_load_translations_early'                => '', // why: translation bootstrap dependency.
		// 'wp_magic_quotes'                           => '', // why: mutates request globals.
		// 'wp_maintenance'                            => '', // why: maintenance bootstrap/output dependency.
		// 'wp_not_installed'                          => '', // why: install/bootstrap + output dependency.
		// 'wp_populate_basic_auth_from_authorization_header' => '', // why: request/auth header mutation.
		// 'wp_set_internal_encoding'                  => '', // why: global runtime encoding mutation.
		// 'wp_set_lang_dir'                           => '', // why: translation/bootstrap path mutation.
		// 'wp_set_wpdb_vars'                          => '', // why: hard $wpdb dependency.
		// 'wp_skip_paused_plugins'                    => '', // why: recovery mode/plugin runtime dependency.
		// 'wp_skip_paused_themes'                     => '', // why: recovery mode/theme runtime dependency.
		// 'wp_start_object_cache'                     => '', // why: object-cache bootstrap dependency.
		// 'wp_start_scraping_edited_file_errors'      => '', // why: admin/editor runtime dependency.
		// 'wp_using_ext_object_cache'                 => '', // why: object-cache runtime dependency.
		// 'wp_using_themes'                           => '', // why: theme bootstrap state dependency.
	],
	'wp-includes/compat.php' => [
		'_'                  => '',
		'_is_utf8_charset'   => '',
		'_wp_can_use_pcre_u' => '',
		'_mb_substr'         => '',
		'_mb_strlen'         => '',
		'mb_substr'          => '',
		'mb_strlen'          => '',
		'is_countable'       => '',
		'array_key_first'    => '',
		'array_key_last'     => '',
		'array_is_list'      => '',
		'str_contains'       => '',
		'str_starts_with'    => '',
		'str_ends_with'      => '',
		'array_find'         => '',
		'array_find_key'     => '',
		'array_any'          => '',
		'array_all'          => '',
	],
	'wp-includes/plugin.php' => [
		// hooks
		'add_filter'                  => '',
		'_wp_call_all_hook'           => '',
		'apply_filters'               => '',
		'apply_filters_deprecated'    => '',
		'apply_filters_ref_array'     => '',
		'has_filter'                  => '',
		'remove_filter'               => '',
		'remove_all_filters'          => '',
		'current_filter'              => '',
		'doing_filter'                => '',
		'did_filter'                  => '',
		'add_action'                  => '',
		'do_action'                   => '',
		'do_action_deprecated'        => '',
		'do_action_ref_array'         => '',
		'has_action'                  => '',
		'remove_action'               => '',
		'remove_all_actions'          => '',
		'current_action'              => '',
		'doing_action'                => '',
		'did_action'                  => '',
		'wp_register_plugin_realpath' => '',
		'plugin_basename'             => '',
		'plugin_dir_path'             => '',
		'plugin_dir_url'              => '',
		'register_activation_hook'    => '',
		'register_deactivation_hook'  => '',
		'register_uninstall_hook'     => '',
		'_wp_filter_build_unique_id'  => '',
	],
	'wp-includes/link-template.php' => [
		'home_url'            => '',
		'get_home_url'        => '',
		'site_url'            => '',
		'get_site_url'        => '',
		'wp_internal_hosts'   => '',
		'wp_is_internal_link' => '',
		'set_url_scheme'      => '',
		'plugins_url'         => '',
		'content_url'         => '',
		'includes_url'        => '',
		// Missing in config, kept for visibility because not suitable for isolated PHPUnit env:
		// '_get_page_link'                => '', // why: requires WP query/post permalink runtime.
		// '_navigation_markup'            => '', // why: depends on theme/template rendering context.
		// 'adjacent_post_link'            => '', // why: requires post loop/query runtime.
		// 'adjacent_posts_rel_link'       => '', // why: requires post loop/query runtime.
		// 'adjacent_posts_rel_link_wp_head' => '', // why: wp_head/output hook dependency.
		// 'admin_url'                     => '', // why: admin bootstrap/runtime dependency.
		// 'edit_bookmark_link'            => '', // why: admin capability/bookmark runtime dependency.
		// 'edit_comment_link'             => '', // why: comment/capability runtime dependency.
		// 'edit_post_link'                => '', // why: post/capability runtime dependency.
		// 'edit_tag_link'                 => '', // why: taxonomy/admin runtime dependency.
		// 'edit_term_link'                => '', // why: taxonomy/admin runtime dependency.
		// 'get_adjacent_post'             => '', // why: DB/query runtime dependency.
		// 'get_adjacent_post_link'        => '', // why: DB/query runtime dependency.
		// 'get_adjacent_post_rel_link'    => '', // why: DB/query runtime dependency.
		// 'get_admin_url'                 => '', // why: admin bootstrap/runtime dependency.
		// 'get_attachment_link'           => '', // why: attachment/post runtime dependency.
		// 'get_author_feed_link'          => '', // why: author query runtime dependency.
		// 'get_avatar_data'               => '', // why: user/avatar runtime dependency chain.
		// 'get_avatar_url'                => '', // why: user/avatar runtime dependency chain.
		// 'get_boundary_post'             => '', // why: DB/query runtime dependency.
		// 'get_category_feed_link'        => '', // why: taxonomy/query runtime dependency.
		// 'get_comments_pagenum_link'     => '', // why: comment query/runtime dependency.
		// 'get_dashboard_url'             => '', // why: admin bootstrap/runtime dependency.
		// 'get_day_link'                  => '', // why: rewrite/query runtime dependency.
		// 'get_delete_post_link'          => '', // why: nonce/capability runtime dependency.
		// 'get_edit_bookmark_link'        => '', // why: admin capability/bookmark runtime dependency.
		// 'get_edit_comment_link'         => '', // why: comment/capability runtime dependency.
		// 'get_edit_post_link'            => '', // why: post/capability runtime dependency.
		// 'get_edit_profile_url'          => '', // why: user/admin runtime dependency.
		// 'get_edit_tag_link'             => '', // why: taxonomy/admin runtime dependency.
		// 'get_edit_term_link'            => '', // why: taxonomy/admin runtime dependency.
		// 'get_edit_user_link'            => '', // why: user/admin runtime dependency.
		// 'get_feed_link'                 => '', // why: rewrite/query runtime dependency.
		// 'get_month_link'                => '', // why: rewrite/query runtime dependency.
		// 'get_next_comments_link'        => '', // why: comment query/runtime dependency.
		// 'get_next_post'                 => '', // why: post query/runtime dependency.
		// 'get_next_post_link'            => '', // why: post query/runtime dependency.
		// 'get_next_posts_link'           => '', // why: query pagination runtime dependency.
		// 'get_next_posts_page_link'      => '', // why: query pagination runtime dependency.
		// 'get_page_link'                 => '', // why: post/query permalink runtime dependency.
		// 'get_pagenum_link'              => '', // why: query/request runtime dependency.
		// 'get_parent_theme_file_path'    => '', // why: theme filesystem/runtime dependency.
		// 'get_parent_theme_file_uri'     => '', // why: theme filesystem/runtime dependency.
		// 'get_permalink'                 => '', // why: post/query permalink runtime dependency.
		// 'get_post_comments_feed_link'   => '', // why: post/comment query runtime dependency.
		// 'get_post_permalink'            => '', // why: post/query permalink runtime dependency.
		// 'get_post_type_archive_feed_link' => '', // why: post-type/rewrite runtime dependency.
		// 'get_post_type_archive_link'    => '', // why: post-type/rewrite runtime dependency.
		// 'get_posts_nav_link'            => '', // why: query pagination runtime dependency.
		// 'get_preview_post_link'         => '', // why: preview/nonces/runtime dependency.
		// 'get_previous_comments_link'    => '', // why: comment query/runtime dependency.
		// 'get_previous_post'             => '', // why: post query/runtime dependency.
		// 'get_previous_post_link'        => '', // why: post query/runtime dependency.
		// 'get_previous_posts_link'       => '', // why: query pagination runtime dependency.
		// 'get_previous_posts_page_link'  => '', // why: query pagination runtime dependency.
		// 'get_privacy_policy_url'        => '', // why: options/page runtime dependency.
		// 'get_search_comments_feed_link' => '', // why: search query/runtime dependency.
		// 'get_search_feed_link'          => '', // why: search query/runtime dependency.
		// 'get_search_link'               => '', // why: search query/runtime dependency.
		// 'get_tag_feed_link'             => '', // why: taxonomy/query runtime dependency.
		// 'get_term_feed_link'            => '', // why: taxonomy/query runtime dependency.
		// 'get_the_comments_navigation'   => '', // why: comments/template runtime dependency.
		// 'get_the_comments_pagination'   => '', // why: comments/template runtime dependency.
		// 'get_the_permalink'             => '', // why: post loop/runtime dependency.
		// 'get_the_post_navigation'       => '', // why: post loop/runtime dependency.
		// 'get_the_posts_navigation'      => '', // why: query/template runtime dependency.
		// 'get_the_posts_pagination'      => '', // why: query/template runtime dependency.
		// 'get_the_privacy_policy_link'   => '', // why: options/page/template runtime dependency.
		// 'get_theme_file_path'           => '', // why: theme filesystem/runtime dependency.
		// 'get_theme_file_uri'            => '', // why: theme filesystem/runtime dependency.
		// 'get_year_link'                 => '', // why: rewrite/query runtime dependency.
		// 'is_avatar_comment_type'        => '', // why: avatar/comment runtime dependency chain.
		// 'network_admin_url'             => '', // why: multisite admin runtime dependency.
		// 'network_home_url'              => '', // why: multisite runtime dependency.
		// 'network_site_url'              => '', // why: multisite runtime dependency.
		// 'next_comments_link'            => '', // why: comment query/runtime dependency.
		// 'next_post_link'                => '', // why: post query/runtime dependency.
		// 'next_post_rel_link'            => '', // why: post query/runtime dependency.
		// 'next_posts'                    => '', // why: query pagination runtime dependency.
		// 'next_posts_link'               => '', // why: query pagination runtime dependency.
		// 'paginate_comments_links'       => '', // why: comment pagination/template runtime dependency.
		// 'permalink_anchor'              => '', // why: post permalink runtime dependency.
		// 'post_comments_feed_link'       => '', // why: post/comment query runtime dependency.
		// 'posts_nav_link'                => '', // why: query pagination runtime dependency.
		// 'prev_post_rel_link'            => '', // why: post query/runtime dependency.
		// 'previous_comments_link'        => '', // why: comment query/runtime dependency.
		// 'previous_post_link'            => '', // why: post query/runtime dependency.
		// 'previous_posts'                => '', // why: query pagination runtime dependency.
		// 'previous_posts_link'           => '', // why: query pagination runtime dependency.
		// 'rel_canonical'                 => '', // why: query/wp_head output runtime dependency.
		// 'self_admin_url'                => '', // why: admin bootstrap/runtime dependency.
		// 'the_comments_navigation'       => '', // why: echoes template output (runtime side effects).
		// 'the_comments_pagination'       => '', // why: echoes template output (runtime side effects).
		// 'the_feed_link'                 => '', // why: echoes template output (runtime side effects).
		// 'the_permalink'                 => '', // why: echoes template output (runtime side effects).
		// 'the_post_navigation'           => '', // why: echoes template output (runtime side effects).
		// 'the_posts_navigation'          => '', // why: echoes template output (runtime side effects).
		// 'the_posts_pagination'          => '', // why: echoes template output (runtime side effects).
		// 'the_privacy_policy_link'       => '', // why: echoes template output (runtime side effects).
		// 'the_shortlink'                 => '', // why: echoes template output (runtime side effects).
		// 'user_admin_url'                => '', // why: user-admin runtime dependency.
		// 'user_trailingslashit'          => '', // why: rewrite/runtime dependency chain.
		// 'wp_force_plain_post_permalink' => '', // why: post/rewrite runtime dependency.
		// 'wp_get_canonical_url'          => '', // why: post/query runtime dependency.
		// 'wp_get_shortlink'              => '', // why: post/query runtime dependency.
		// 'wp_shortlink_header'           => '', // why: HTTP header/output runtime dependency.
		// 'wp_shortlink_wp_head'          => '', // why: wp_head/output hook runtime dependency.
	],
	'wp-includes/default-constants.php' => [
		'wp_initial_constants'          => '',
		'wp_plugin_directory_constants' => '',
		'wp_cookie_constants'           => '',
		'wp_ssl_constants'              => '',
		'wp_functionality_constants'    => '',
		// 'wp_templating_constants'       => '', // get_template_directory() dependency
	],
	'wp-includes/http.php' => [
		'wp_parse_url' => '',
		'_wp_translate_php_url_constant_to_key' => '',
		'_get_component_from_parsed_url_array' => '',
		// Missing in config, kept for visibility because not suitable for isolated PHPUnit env:
		// '_wp_http_get_object'            => '', // why: requires WP_HTTP class stack/runtime.
		// 'allowed_http_request_hosts'     => '', // why: HTTP policy/runtime dependency.
		// 'get_allowed_http_origins'       => '', // why: CORS/runtime dependency.
		// 'get_http_origin'                => '', // why: request header runtime dependency.
		// 'is_allowed_http_origin'         => '', // why: CORS/runtime dependency.
		// 'ms_allowed_http_request_hosts'  => '', // why: multisite runtime dependency.
		// 'send_origin_headers'            => '', // why: sends headers/output side effects.
		// 'wp_http_supports'               => '', // why: transport/runtime dependency.
		// 'wp_http_validate_url'           => '', // why: HTTP policy/runtime dependency.
		// 'wp_remote_get'                  => '', // why: network I/O dependency.
		// 'wp_remote_head'                 => '', // why: network I/O dependency.
		// 'wp_remote_post'                 => '', // why: network I/O dependency.
		// 'wp_remote_request'              => '', // why: network I/O dependency.
		// 'wp_remote_retrieve_body'        => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_cookie'      => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_cookie_value' => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_cookies'     => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_header'      => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_headers'     => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_response_code' => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_remote_retrieve_response_message' => '', // why: requires WP_HTTP response objects/runtime.
		// 'wp_safe_remote_get'             => '', // why: network I/O dependency.
		// 'wp_safe_remote_head'            => '', // why: network I/O dependency.
		// 'wp_safe_remote_post'            => '', // why: network I/O dependency.
		// 'wp_safe_remote_request'         => '', // why: network I/O dependency.
	],
	'wp-includes/l10n.php' => [
		'_n_noop'                    => '',
		'_nx_noop'                   => '',
		'is_rtl'                     => '',
		'translate_nooped_plural'    => '',
		// 'determine_locale'           => '', // why: depends on is_admin() runtime context.
		'get_locale'                 => '',
		'wp_get_list_item_separator' => '',
		'wp_get_word_count_type'     => '',
		'before_last_bar'            => '',
		// '__'         => '', // mocked
		// '_e'         => '', // mocked
		// '_x'         => '', // mocked
		// '_n'         => '', // mocked
		// '_nx'        => '', // mocked
		// 'esc_html__' => '', // mocked
		// 'esc_html_e' => '', // mocked
		// 'esc_html_x' => '', // mocked
		// 'esc_attr__' => '', // mocked
		// 'esc_attr_e' => '', // mocked
		// 'esc_attr_x' => '', // mocked
		// Missing in config, kept for visibility because not suitable for isolated PHPUnit env:
		// '_ex'                          => '', // why: i18n runtime dependency (context translation).
		// '_load_textdomain_just_in_time' => '', // why: textdomain loading/filesystem/runtime dependency.
		// 'get_available_languages'      => '', // why: language pack filesystem dependency.
		// 'get_translations_for_domain'  => '', // why: translation registry/runtime dependency.
		// 'get_user_locale'              => '', // why: user/session runtime dependency.
		// 'has_translation'              => '', // why: translation registry/runtime dependency.
		// 'is_locale_switched'           => '', // why: locale switching runtime dependency.
		// 'is_textdomain_loaded'         => '', // why: translation registry/runtime dependency.
		// 'load_child_theme_textdomain'  => '', // why: theme/filesystem runtime dependency.
		// 'load_default_textdomain'      => '', // why: default translation files/runtime dependency.
		// 'load_muplugin_textdomain'     => '', // why: plugin/filesystem runtime dependency.
		// 'load_plugin_textdomain'       => '', // why: plugin/filesystem runtime dependency.
		// 'load_script_textdomain'       => '', // why: script translation files/runtime dependency.
		// 'load_script_translations'     => '', // why: script translation files/runtime dependency.
		// 'load_textdomain'              => '', // why: MO/PHP translation file loading dependency.
		// 'load_theme_textdomain'        => '', // why: theme/filesystem runtime dependency.
		// 'restore_current_locale'       => '', // why: locale switching runtime dependency.
		// 'restore_previous_locale'      => '', // why: locale switching runtime dependency.
		// 'switch_to_locale'             => '', // why: locale switching runtime dependency.
		// 'switch_to_user_locale'        => '', // why: user/session + locale runtime dependency.
		// 'translate'                    => '', // why: full translation registry/runtime dependency.
		// 'translate_settings_using_i18n_schema' => '', // why: settings/i18n schema runtime dependency.
		// 'translate_user_role'          => '', // why: roles/capabilities + translation runtime dependency.
		// 'translate_with_gettext_context' => '', // why: full translation registry/runtime dependency.
		// 'unload_textdomain'            => '', // why: translation registry/runtime dependency.
		// 'wp_dropdown_languages'        => '', // why: admin UI + translation files/runtime dependency.
		// 'wp_get_installed_translations' => '', // why: translation files/filesystem dependency.
		// 'wp_get_l10n_php_file_data'    => '', // why: translation file parsing/filesystem dependency.
		// 'wp_get_pomo_file_data'        => '', // why: translation file parsing/filesystem dependency.
	],
];
